version: "3.6"
services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    image: "postgres:9.6"
    environment:
      - "POSTGRES_PASSWORD=Password12!"
    ports:
      - 5432:5432
  redis:
    image: "redis"
    ports:
      - 6379:6379
  service:
    image: jobservice/service
    build:
      context: ./src
      dockerfile: Dockerfile.service
    environment:
      - "ConnectionStrings__JobService=host=postgres;user id=postgres;password=Password12!;database=jobservice;"
    ports:
     - "5000:80"
     - "5001:81"
